### ISSUE TITLE
Ti SDK 9.3.2.GA + ti.crashlytics 2.1.0 Android = NullPointerException on start up

### ISSUE THREAD

**Issue by phillipmovista** [hansemannn/titanium-crashlytics#38] opened 2021-09-17 18:52 UTC
Thank you all so much for these modules!

I am working on getting ti.crashlytics 2.1.0 into my Android app. I used the basic `require('ti.crashlytics');` in the code and I do see it going to Crashlytics in Firebase, but oddly enough, it immediately fires off a crash of:

`Non-fatal Exception: java.lang.Exception`

```
Non-fatal Exception: java.lang.Exception
       at ti.crashlytics.TitaniumCrashlyticsModule.onAppCreate(TitaniumCrashlyticsModule.java:50)
```

This seems pretty odd since it got to Firebase okay, but then it seems to complain that something in this line is not playing well:

`FirebaseCrashlytics.getInstance().recordException(new Exception());`

Thanks so much!

**Comment by macasfaj** [comment] 2021-09-17 18:58
I have the same issue. I was taking about it with @m1ga recently 😞

**Comment by m1ga** [comment] 2021-09-17 20:04
@phillipmovista that line was recommended as a workaround by users in the firbase native users and it should trigger a push to upload all stored exceptions. But the problem is that it is the only exception we are seeing now. Other exceptions are not logged or seen.

Looks like it is not a Titanium only issue: https://github.com/firebase/firebase-android-sdk/issues/1944#issuecomment-883630065 but hopefully we can find a way around it. 

There is a Sentry module https://github.com/AppWerft/Ti.Sentry which might be worth updating

**Comment by phillipmovista** [comment] 2021-09-17 20:09
I was looking at it and wondering what caused the NullPointerException. Maybe `FirebaseCrashlytics.getInstance()` is null at the time that is called or something?

We already have newrelic in place but we are having to jump off it since I suppose they do not support Android Ti SDK 9

**Comment by m1ga** [comment] 2021-09-17 20:11
its `new Exception()` inside `recordException` :wink: That throws the exception and triggers the connection to the server. But it should upload all other exceptions too which is not happening

**Comment by phillipmovista** [comment] 2021-09-17 20:14
Oh, super weird. I have this running first thing in my app (to load up crashlytics) maybe that has something to do with it? Possible that it needs to check for if any exceptions exist to upload and then send them?

**Comment by m1ga** [comment] 2021-09-17 20:26
normally you don't need that and it should upload logs by its own. But it stopped working so we had a look and found that issue above where other (native) people have the same issue. 
But again: the exception is intended but it should upload more which it doesn't. We've tried other workarounds but it all ended up in just seeing that crashlog and no other logs.

Have to do some more tests and check if there is any workaround or if we have to wait for the next version of crashlytics

**Comment by phillipmovista** [comment] 2021-09-17 20:27
Sound good, thank you. I will hopefully see an updated version as well.

**Comment by m1ga** [comment] 2021-09-17 20:30
You can try this version: https://migaweb.de/ti.crashlytics-android-2.1.1.zip where I removed the `FirebaseCrashlytics.getInstance().recordException(new Exception());` So it is the "old" version with the latest dependencies. There was no log at all in our tests, perhaps you'll have more luck with it

**Comment by phillipmovista** [comment] 2021-09-17 20:42
2.1.1 is acting the same for me - thanks for trying.

**Comment by m1ga** [comment] 2021-09-17 20:52
wait, with the init exception again or just no results?

**Comment by phillipmovista** [comment] 2021-09-17 20:54
init exception. still same error as above.

**Comment by m1ga** [comment] 2021-09-17 20:56
that code shouldn't be in there :thinking: Try this one https://migaweb.de/ti.crashlytics-android-2.1.1b.zip perhaps I've uploaded the wrong file

**Comment by phillipmovista** [comment] 2021-09-17 21:07
Initial tests show this is better. I will keep at it for another half hour or so

**Comment by m1ga** [comment] 2021-09-21 09:57
@phillipmovista you could run `.crash()` from the module to force a crash. Would be good to know if that is working for you

**Comment by phillipmovista** [comment] 2021-09-21 13:52
It does show the program crashes but then I do not see anything showing up in crashlytics after that time.

**Comment by phillipmovista** [comment] 2021-09-21 14:30
Darn, well, thank you for letting me know. I will share this with my team since we have other apps that may be wanting this same functionality and it looks like there could be other issues with crashlytics in mobile apps.

**Comment by phillipmovista** [comment] 2021-09-23 16:33
@m1ga any chance you can link me to that other firebase repo discussion?

Also, is there anything we can do to have the `2.1.1` code to see the steps that are being taken on this?

**Comment by m1ga** [comment] 2021-09-23 16:36
link is mentioned here https://github.com/hansemannn/titanium-crashlytics/issues/38#issuecomment-922049998

The whole module code is just those lines:
https://github.com/hansemannn/titanium-crashlytics/blob/master/android/src/ti/crashlytics/TitaniumCrashlyticsModule.java#L24-L51
and I just removed the line `FirebaseCrashlytics.getInstance().recordException(new Exception());` again

**Comment by phillipmovista** [comment] 2021-09-23 16:56
Thank you, I had overlooked that by mistake. We will keep digging from there.

**Comment by petenathan42** [comment] 2021-10-05 21:22
crashlytics 18.2.3 is out:
https://mvnrepository.com/artifact/com.google.firebase/firebase-crashlytics?repo=google

along with analytics 19.0.2
https://mvnrepository.com/artifact/com.google.firebase/firebase-analytics?repo=google

If you want to give it a shot Still not a lot of luck from my end, but wanted to share!

**Comment by m1ga** [comment] 2021-10-05 21:55
Thanks for the info @petenathan42 nothing in my logs either and I don't see any release logs of 18.2.3

**Comment by petenathan42** [comment] 2021-10-06 23:02
I can't really tell if this is a crashlytics issue or something funky going on with how it's integrated with titanium. You would expect an event to be created with a fatal test crash, but there's absolute silence in the firebase logs

long explanation posted in the bigger thread: 

I am getting the:
10-06 17:03:17.538 19155 19193 V FirebaseCrashlytics: Persisting non-fatal event for session 615E1CC3033500014AD34B023E324821
log when running:
FirebaseCrashlytics.getInstance().recordException(new RuntimeException("test crash"));
In my test crash function.

the "Persisting non-fatal event for session" occurrence, on android, creates an event file in:
/data/user/0/<app-name>/files/.com.google.firebase.crashlytics/report-persistence/sessions/<session>/
the file name in my case was "event0000000000"

So after you restart the application, a report is created based on that event and then that report is sent to the firebase console.

However,

When I run my test crash function in the same place, but instead with a fatal crash:
throw new RuntimeException("test crash");
I just get silence in the log. Why isn't an event being created in this situation? An event is never created, so a report is never created, and so I never get anything in the firebase console.

I'm using
Crashlytics 18.2.1 (also tried 18.2.3)
Analytics 19.0.1 (also tried 19.0.2)
Firebase Crashlytics Gradle 2.7.1

FYI, to get the verbose logs, run the command:
adb shell setprop log.tag.FirebaseCrashlytics VERBOSE
Then, run the
adb logcat -s FirebaseCrashlytics TransportRuntime.SQLiteEventStore TransportRuntime.JobInfoScheduler TransportRuntime.CctTransportBackend TransportRuntime.DefaultScheduler

to see the file system, run
adb shell
as root, and navigate to /data/user/0/<app name>/files/.com.google.firebase.crashlytics/report-persistence/

**Comment by m1ga** [comment] 2021-10-06 23:31
as you can see in the native thread where you've posted too: there are native people having the same issues and there was team member post that they can reproduce the error (20 Jul) but that workaround didn't really work. It will just send a new exception but not the log you'll want to have. So I don't know any solution at the moment

**Comment by petenathan42** [comment] 2021-10-07 03:20
I'm not sure if the issue I am having is the same one as in that native thread. It seems like they are getting events written in device storage, but the sending is failing. My problem is that a crash event isn't ever being written to the device's file system. 

In the example project reference by the 20 Jul comment (Jan 27), he's saying the report is failing to send depending on how late the crash occurs in the app. 

In my example, I'm never getting any crash data written, no matter how late in the app I run the test crash. 

I would be interested to know what happens in your `adb shell setprop log.tag.FirebaseCrashlytics VERBOSE` log when running a test crash. Any sign of life in the log at the point of the crash would already be better than what I'm getting.

**Comment by petenathan42** [comment] 2021-10-09 03:41
I expanded on that idea a bit. I have formatted the stack trace that crashlystics consumes with titaniums's error.javaStack and error.jsStack in mind. The top-level error is still `new StackTraceElement(errorSourceName, errorMessage, errorLineSource, errorLine);`, but now the stack trace also includes error.javaStack and error.jsStack

I noticed that sometimes error.javaStack is null, so I just took care of all 4 cases.

both error.javaStack and error.jsStack exist:
![image](https://user-images.githubusercontent.com/48021464/136642612-9452fecc-4edd-40b6-9d2b-ec67ad7cdcc8.png)

only error.javaStack exists:
![image](https://user-images.githubusercontent.com/48021464/136642654-1496278a-2020-4625-9321-a59afbd98cca.png)

only error.jsStack exists:
![image](https://user-images.githubusercontent.com/48021464/136642668-f15492ed-ccdf-4687-afbf-fc3c3272ebb8.png)

no stack available:
![image](https://user-images.githubusercontent.com/48021464/136642712-66b3dec9-88d7-41d5-bde0-b730ba980917.png)


module code:
```
	public static StackTraceElement[] generateStackTrace(String javaStack, String jsStack, String errorSourceName, String errorMessage, String errorLineSource, int errorLine) {
		String javaHeader = "------------------------------JAVA STACK.TRACE------------------------------(JAVA STACK.TRACE:0)" + System.lineSeparator();
		String jsHeader = "------------------------JAVACRIPT STACK.TRACE------------------------(JAVASCRIPT STACK.TRACE:0)" + System.lineSeparator();
		String bigStack;
		
		if (javaStack != null && jsStack != null) {
			bigStack = javaHeader + javaStack.substring(javaStack.indexOf(System.lineSeparator()) + 1) + jsHeader + jsStack.substring(jsStack.indexOf(System.lineSeparator()) + 1);
		} else if (javaStack != null) {
			bigStack = javaHeader + javaStack.substring(javaStack.indexOf(System.lineSeparator()) + 1);
		} else if (jsStack != null) {
			bigStack = jsHeader + jsStack.substring(jsStack.indexOf(System.lineSeparator()) + 1);
		} else {
			StackTraceElement[] trace = new StackTraceElement[] {
				new StackTraceElement(errorSourceName, errorMessage, errorLineSource, errorLine)
			};
			return trace;
		}
		
		String[] stackElements = bigStack.split(System.lineSeparator());
		StackTraceElement[] trace = new StackTraceElement[stackElements.length + 1];
		trace[0] = new StackTraceElement(errorSourceName, errorMessage, errorLineSource, errorLine);
		for (int i = 0; i < stackElements.length; i++) {
			Log.i(TAG, "javaStackElements " + i + ": " + stackElements[i]);
			String[] splitByParen = stackElements[i].substring(0, stackElements[i].length() - 1).split("\\(");
				
			String fileName = "";
			int lineNumber = 0;
			if (splitByParen[1].indexOf(":") > -1) {
				String[] insideParen = splitByParen[1].split(":");
				Log.i(TAG, "insideParen: " + insideParen);
				for (int j = 0; j < insideParen.length; j++) {
					if ((insideParen[j].matches("[0-9]+"))) {
				                // within the parenthesis, the first number is the line number, for both javaStack and jsStack
				                lineNumber = Integer.parseInt(insideParen[j]);
				                break;
					} else {
				                // within the parenthesis, everything before first number is the fileName
				                fileName += insideParen[j] + ":";
				        }
				}
				// remove extra ":"
				fileName = fileName.substring(0, fileName.length() - 1);
			} else {
				fileName = splitByParen[1];
				lineNumber = 0;
			}
						
			String declaringClass;
			String methodName;
			if (splitByParen[0].indexOf(splitByParen[1].split("\\.")[0]) > -1) {
				declaringClass = splitByParen[0].substring(0, splitByParen[0].indexOf(splitByParen[1].split("\\.")[0]) - 1).trim();
				methodName = splitByParen[0].substring(splitByParen[0].indexOf(splitByParen[1].split("\\.")[0]));
			} else {
				declaringClass = splitByParen[0].substring(0, splitByParen[0].lastIndexOf('.')).trim();
				methodName = splitByParen[0].substring(splitByParen[0].lastIndexOf('.') + 1);
			}
				
			trace[i+1] = new StackTraceElement(declaringClass, methodName, fileName, lineNumber);
	    }
			
		return trace;
	}
	
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		KrollRuntime.setPrimaryExceptionHandler(new TiExceptionHandler(){
			@Override
			public void handleException(ExceptionMessage error)
			{
				Throwable th = new Throwable();
				th.setStackTrace(generateStackTrace(error.javaStack, error.jsStack, error.sourceName, error.message, error.lineSource, error.line));
				FirebaseCrashlytics.getInstance().recordException(th);
				super.handleException(error);
			}
		});
	}

```

**Comment by m1ga** [comment] 2021-10-09 11:29
@petenathan42 would you mind cleaning that up (tabs/spaces), remove the jsHeader/javaHeader to make it a bit cleaner, remove the log.i and then submit a PR?

**Comment by petenathan42** [comment] 2021-10-15 17:06
@m1ga Sorry for the delay, I took some PTO.
I tried to create a PR, but got this access error:
![image](https://user-images.githubusercontent.com/48021464/137525996-dd2864bd-5aaa-4248-b69c-371d410dd0d5.png)

**Comment by petenathan42** [comment] 2021-10-15 17:14
@m1ga 
https://github.com/hansemannn/titanium-crashlytics/pull/39

**Comment by m1ga** [comment] 2021-10-16 11:01
Merged & fixed. Thanks @petenathan42 :+1:

**Closed by m1ga** 2021-10-16 11:01 UTC
